// examples/react-zusmodule-host-app/src/pages/NotFoundPage.tsx
import { Button, Result } from 'antd'
import { useNavigate } from 'react-router-dom'

export function NotFoundPage() {
  const navigate = useNavigate()
  return (
    <Result
      status="404"
      title="404"
      subTitle="当前路径不存在。"
      extra={
        <Button type="primary" onClick={() => navigate('/dashboard')}>
          返回工作台
        </Button>
      }
    />
  )
}

// examples/vue3-zusmodule-host-app/src/pages/NotFoundPage.vue
<script setup lang="ts">
import { Button, Result } from 'ant-design-vue'
import { useRouter } from 'vue-router'

const router = useRouter()

function goDashboard() {
  router.push('/dashboard')
}
</script>

<template>
  <Result
    status="404"
    title="404"
    sub-title="当前路径不存在。"
  >
    <template #extra>
      <Button type="primary" @click="goDashboard">返回工作台</Button>
    </template>
  </Result>
</template>
